PPI_ADVERBS = [
    'pretty',
    'fairly',
    'rather',
    'somewhat',
    'kinda',
    'sorta'
]

ADV_OF_INTEREST = [
    'slightly',
    'partially',
    'minimally',
    'marginally',
    'weakly',
    'modestly',
    'moderately',
    'underwhelmingly',
    'acceptably',
    'adequately',
    'passingly',
    'passing',
    'satisfactorily',
    'reasonably',
    'tolerably',
    'dubiously',
    'supposedly',

    'exactly',
    'precisely',

    'very',
    'really',
    'quite',

    'hugely',
    'largely',
    'greatly',
    'highly',
    'deeply',
    'widely',
    'strongly',
    'super',

    'particularly',
    'especially',
    'entirely',
    'extremely',
    'notably',

    'amazingly',
    'heartily',
    'impressively',
    'marvelously',
    'extraordinarily',
    'splendidly',
    'gloriously',
    'divinely',
    'sensationally',
    'wonderfully',
    'fabulously',
    'fantastically',
    'delectably',
    'deliciously',

    'positively',
    'surely',
    'certainly',
    'actually',
    'definitely',
    'undoubtedly',
    'certifiably',
    'veritably',
    'verifiably',
    'truly',
    'honestly',
    'genuinely',

    'seriously',
    'sincerely',
    'earnestly',
    'hopelessly',

    'obviously',
    'clearly',
    'blatantly',
    'openly',

    'horribly',
    'frightfully',
    'scarily',
    'creepily',
    'eerily',
    'spookily',
    'terribly',
    'dreadfully',
    'dangerously',
    'alarmingly',
    'suspiciously',
    'awfully',
    'fucking',

    'disgustingly',
    'morbidly',
    'fatally',
    'miserably',
    'maddeningly',
    'violently',

    'peculiarly',
    'strangely',
    'freakishly',
    'weirdly',
    'oddly',
    'ridiculously',
    'bizarrely',
    'absurdly',

    'crazy',
    'crazily',
    'insanely',
    'madly',
    'incredibly',
    'unbelievably',
    'impossibly',

    'disconcertingly',
    'troublingly',
    'worryingly',
    'disturbingly',

    'inordinately',
    'excessively',
    'overly',
    'overwhelmingly',
    'intolerably',
    'unacceptably',

    'utterly',
    'completely',
    'totally',
    'maximally',
    'perfectly',

    # Morzycki's EDM
    'simply',
    'just',
    'positively',
    'absolutely',
    'downright',
    'outright',
    'flat-out',
    'full-on',
    'out-and-out',
    'straight-up',
    'balls-out',

    # M-modifiers (Solt & Wilson 2021)
    'pretty',
    'fairly',
    'rather',
    'somewhat',
    'kinda',
    'sorta',

    # NegPol Triggers
    'scarcely',
    'barely',
    'hardly',
    'rarely',
    # 'no',
    'not',
    'never',

    # minimal pairs?
    'always',
    'some',
    'often',
    'frequently',
    'normally',
    'usually',
    'typically',
    'commonly',

    # NPI or "rescuer"
    'yet',
    'even',
    'only',
    'enough',
    'too',
]


ADJ_BY_SCALE = {
    'NON_G': ('dead',
              'alive',
              'existing',
              'extinct',
              'pregnant'),
    'OPEN': ('big',
             'large',
             'small',
             'cheap',
             'expensive',
             'deep',
             'shallow',
             'fat',
             'thin',
             'long',
             'short',
             'tall',
             'rich',
             'poor',
             'strong',
             'weak',
             'wide',
             'narrow',
             'loud',
             'quiet',
             'soft',
             'hard',
             'high',
             'low'
             ),
    'LOW_CLOSE': ('bent',
                  'bumpy',
                  'crooked',
                  'dangerous',
                  'dirty',
                  'impure',
                  'incomplete',
                  'wet'),
    'UP_CLOSE': ('straight',
                 'smooth',
                 'safe',
                 'clean',
                 'pure',
                 'complete',
                 'dry'),
    'TOT_CLOSE': ('open',
                  'closed',
                  'full',
                  'empty',
                  'opaque',
                  'transparent')
}
